### ISSUE TITLE
A lot of crashes in Inner-active ad control

### ISSUE THREAD

**Issue by korzh** [Adrotator/AdrotatorV2#26]
It's a WP 7.1 application.
BugSense reports of numerous crashes inside Inner-active ad control. Inner-active is one of networks we have configured via AdRotator control.
I think the best approach will be:
1. To catch all possible exceptions from all ad controls (including Inner-active)
2. If some ad-control crashed - turn to another network regardless the current Probability setting.

**Comment by SimonDarksideJ** [comment]
hmm. although we do catch Ad Failures and then remove them from circulation, we don't remove them just for causing exceptions.
Some Ad Provider controls use exceptions in odd ways (including pubcentre) this would likely stop you using that ad provider.

If you feel an Ad Provider is not behaving how you would want them to, then either stop using that provider or raise an issue with the Ad Providers control on their site.

Do the errors occur when not using Ad Rotator with Inneractive?

**Comment by korzh** [comment]
1. I think the exceptions occur not all the time but in some conditions (bad Inet connection,  a particular version of OS, etc). So it would be a good idea to decrease or even remove such this provider from rotation automatically if it crashes too much.
2. We did contacted Inner-active with this issue. No response for now.
3. No, we didn't test it without Ad Rotator. And it's quite difficult to stop using it (there some not-technical issues).

**Comment by SimonDarksideJ** [comment]
If you have AdRotator, stopping using a single provider is easy, just remove it from your config XML or set it's probability to zero.
As for testing the control without AdRotator, simply create a new blank project and test with your Inneractive credentials

**Comment by korzh** [comment]
I know how to remove some provider from AdRotator and how to test it separately.
I'm just saying that it's difficult to avoid using that provider because of some non-technical issues.

**Comment by SimonDarksideJ** [comment]
Right, I get you now.
You could try using AdDuplex as a fallback / alternative while Inneractive resolve their control, possibly.
Hope this helps.

**Comment by korzh** [comment]
We do it now, actually. :)

**Comment by SimonDarksideJ** [comment]
So can this issue be closed?
Is the problem with AdRotator or with Inneractive's own control in your project?

**Comment by korzh** [comment]
The problem is in AdRotator but in most cases it occurs when Inneractive ads are shown.
That's why I suggest to consider a possibility for better error handling and automatic adjustment of probability for some provider or even removing it if the problem occurs too often.

**Comment by SimonDarksideJ** [comment]
OK, to better help narrow down where these errors occur, could you provide a stack trace and the output from the debug log.

This will help us a lot, thanks

**Comment by korzh** [comment]
OK. Here is an example:
System.Xml.XmlException: For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.ReadToFollowing(String name)
   at Inneractive.Ad.InneractiveAdControl.ParseCPDXml(String xmlResponse)
   at Inneractive.Ad.InneractiveAdControl.webClient_UploadStringCompleted(Object sender, UploadStringCompletedEventArgs e)
   at System.Net.WebClient.OnUploadStringCompleted(UploadStringCompletedEventArgs e)
   at System.Net.WebClient.UploadStringOperationCompleted(Object arg)
   at BugSense.Core.BugSenseSyncContextHandler.AsyncSynchronizationContext.<>c__DisplayClass5a.<wrapcallback>b__59(Object state)

**Comment by korzh** [comment]
Here is another one:

System.IO.IsolatedStorage.IsolatedStorageException: Operation not permitted on IsolatedStorageFileStream.
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, IsolatedStorageFile isf)
   at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, IsolatedStorageFile isf)
   at System.IO.IsolatedStorage.IsolatedStorageFile.OpenFile(String path, FileMode mode)
   at Inneractive.Ad.InneractiveAdControl.WriteThread(Object obj)
   at System.Threading.ThreadHelper.ThreadStartHelper(ThreadHelper t)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStartHelper()

**Comment by SimonDarksideJ** [comment]
Hmm, looks like Inneractive are doing naughty things in their control.  Will try doing some further testing to see what we can do.
One thing to check is capabilities, ensure you have sufficient CAPS for User Identity and storage (need to double check which caps are used by those exceptions)

Can you verify that in the same app you don't get the above errors when using the control natively?

**Comment by korzh** [comment]
No, we use Inneractive ad control only with AdRotator so I can't verify that.

As for capabilities - we turned them all except PHONEDIALER, GAMERSERVICES and APPOINTMENTS
I don't think these capabilities affects somehow on working with IsoStorage.

**Comment by korzh** [comment]
By the way. As I can see from bug reports (we use BugSense) this error occurred only on devices with version 7.10 of Windows Phone

**Comment by SimonDarksideJ** [comment]
Interesting, if the issue only occurs with WP7.1 it does sound more like an issue with Inneractive's control.
The AdRotator code and function is the same across all platforms for each provider.
